'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const U=require('./general-waste-ui.js'),B=require('./general-waste-daily-bridge.js'),M=require('./general-waste-monthly.cjs');
const p={id:'user',companyId:'company',active:true,role:'admin'},rp={...p,companyName:'検証用会社',address:'検証用住所',permitNumber:'TEST',permitConfirmed:true,reportingMode:'own_carrier'};
function client(data,hook=()=>{}){const calls=[];return {calls,from(table){let company,order;return {select(fields){calls.push({table,fields});return this},eq(k,v){assert.equal(k,'company_id');company=v;return this},order(k,o){order=k;assert.equal(o.ascending,true);return this},async range(a,b){calls.push({a,b,company,order});hook(a);return {data:data.slice(a,b+1),error:null};}};}};}
test('all-company read includes report 501 and ends with the second page',async()=>{const data=Array.from({length:501},(_,i)=>({id:'id'+i,company_id:'company'})),c=client(data);const r=await U.readAllReports(c,p);assert.equal(r.rows.length,501);assert.equal(r.complete,true);assert.equal(c.calls.filter(x=>'a'in x).length,2);assert.ok(c.calls.filter(x=>'a'in x).every(x=>x.company==='company'&&x.order==='id'));});
test('a full 500 page requires a terminal empty-page confirmation',async()=>{const data=Array.from({length:500},(_,i)=>({id:'id'+i,company_id:'company'})),c=client(data);const r=await U.readAllReports(c,p);assert.equal(r.rows.length,500);assert.equal(c.calls.filter(x=>'a'in x).length,2);});
test('failed second page cannot yield a partial successful result',async()=>{const c=client(Array.from({length:501},(_,i)=>({id:String(i),company_id:'company'})),a=>{if(a===500)throw Error('mock read failed')});await assert.rejects(()=>U.readAllReports(c,p),/failed/);});
test('foreign company record is rejected instead of displayed',async()=>{await assert.rejects(()=>U.readAllReports(client([{id:'foreign',company_id:'different'}]),p),/会社/);});
test('duplicate report IDs during pagination cause retry rather than double counting',async()=>{const d=Array.from({length:500},(_,i)=>({id:'id'+i,company_id:'company'}));d.push(d[0]);await assert.rejects(()=>U.readAllReports(client(d),p),/変わりました/);});
test('logout in flight discards read data',async()=>{let active=true;const c=client([{id:'id1',company_id:'company'}],()=>{active=false});await assert.rejects(()=>U.readAllReports(c,p,{isCurrent:()=>active}),/切り替わった/);});
test('employee and signed-out profiles cannot request a company ledger',async()=>{for(const role of ['employee',''])await assert.rejects(()=>U.readAllReports(client([]),{...p,role}),/管理者/);await assert.rejects(()=>U.readAllReports(client([]),{...p,active:false}),/管理者/);});
test('empty successful read is complete, but is not an automatically confirmed zero report',async()=>{const r=await U.readAllReports(client([]),p);const m=B.monthlyFromReports(M,r.rows,'2026-09',rp,{});assert.equal(m.ready,false);assert.equal(m.zeroConfirmed,false);});
test('legacy coverage is evaluated per report month, while deliveries can cross report months',()=>{const old={id:'old',company_id:'company',report_date:'2026-08-01',report_data:{date:'2026-08-01'}};const m=B.monthlyFromReports(M,[old],'2026-09',rp,{});assert.equal(m.coverage.legacyReports,0);assert.equal(B.monthlyFromReports(M,[old],'2026-08',rp,{}).coverage.legacyReports,1);});
test('bridge can mount signed out; ordinary collect and clear still work, protected fill is blocked',()=>{let profile=null,clears=0;const host={collect:()=>({id:1,items:[{name:'existing'}]}),fillReportForm:()=>{},clearReportEditState:()=>clears++};const a=B.bind(host,{getProfile:()=>profile});assert.equal(host.collect().items[0].name,'existing');host.clearReportEditState();assert.equal(clears,1);assert.throws(()=>host.fillReportForm({generalWasteV1:{}}),/ログイン/);profile=p;a.add({},'new-row');assert.equal(a.entries().length,1);});
test('logout and different principal cannot retain prior entry data',()=>{let profile=p;const host={collect:()=>({id:1,date:'2026-09-24',site:'sample'}),fillReportForm:()=>{},clearReportEditState:()=>{}};const a=B.bind(host,{getProfile:()=>profile});a.add({netKg:'250'},'r1');profile=null;assert.equal(host.collect().generalWasteV1,undefined);host.clearReportEditState();profile={...p,id:'another'};assert.deepEqual(a.entries(),[]);});
test('disposing restores wrappers without replacing any newer wrapper',()=>{const host={collect:()=>({ok:1}),fillReportForm:()=> 'fill',clearReportEditState:()=> 'clear'};const orig=host.collect,a=B.bind(host,{getProfile:()=>p}),wrapped=host.collect;host.collect=()=>wrapped();const newer=host.collect;a.dispose();assert.equal(host.collect,newer);assert.deepEqual(host.collect(),{ok:1});assert.equal(host.fillReportForm({generalWasteV1:{}}),'fill');});
