'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const B=require('./general-waste-daily-bridge.js'),M=require('./general-waste-monthly.cjs');
const profile={id:'test-user',companyId:'sample-company',companyName:'検証用会社',active:true,permitConfirmed:true,permitNumber:'TEST',reportingMode:'own_carrier',address:'検証用住所'};
const ordinary={id:1,date:'2026-09-24',site:'検証現場',writer:'検証担当',items:[{name:'産廃：木くず',isWaste:true,qty:'2',unit:'m³',price:'1000'}],siteMoves:[{site:'別現場',waste:'木くず',qty:1}],photos:['test-reference'],futureField:{a:1}};
const good={date:'2026-09-24',siteName:'検証現場',type:'可燃物',facility:'北部清掃処分',municipality:'鹿児島市',vehicleNumber:'検証100あ1',quantity:'250',unit:'kg',netKg:'250',ticketNumber:'TEST-1',scopeConfirmed:true};
const review={sourceComplete:true,weighSlipsReconciled:true,contractReportChecked:true,legacyReportsReconciled:true};
function session(){return new B.Session(profile);}
function report(s,id='daily1'){return {id,company_id:profile.companyId,report_data:s.capture(ordinary,profile)};}
function fixture(){
 const source=fs.readFileSync(path.resolve(__dirname,'../../docs/index.html'),'utf8');
 const extract=(name,next)=>{const start=source.indexOf('function '+name+'('),end=source.indexOf('\n'+(next==='cloudFetchReports'?'async ':'')+'function '+next+'(',start);assert.ok(start>=0&&end>start);return source.slice(start,end);};
 const nodes={};const $=selector=>nodes[selector]??(nodes[selector]={value:'',innerHTML:'',textContent:'',classList:{add(){},remove(){}},click(){}});
 ['date','site','writer','weather','start','end','details','memo','otherWorker','overtime','meikenCount','asahiCount','photoCategory'].forEach(k=>$('#'+k));
 $('#date').value='2026-09-24';$('#site').value='検証現場';$('#writer').value='検証担当';
 const c={$,$$:()=>[],checked:()=>[],esc:String,Date,Number,JSON,Boolean,Array,String,structuredClone,stagedPhotos:[],cloudProfilesCache:{},cloudPhotoCount:{},document:{querySelector:()=>({click(){}})},scrollTo(){},today:()=> '2026-09-24',ensureSiteOption(){},clearReportFormDynamic(){},restoreAttachmentChoices(){},renderMachineHours(){},addLeaseVehicle(){},addLeaseMachine(){},addLeaseAttachment(){},addFuelRow(){},syncFuelInputs(){},addItem(){}};
 c.window=c;c.ToyaCompanyDispatch={entries:()=>[]};vm.createContext(c);vm.runInContext('let editingReport=null;'+extract('collect','validate')+'\n'+extract('clearReportEditState','cancelReportEdit')+'\n'+extract('fillReportForm','editCloudReport')+'\n'+extract('cloudNormalizeReport','cloudFetchReports').replace(/\nasync\s*$/,''),c);
 return {host:c,$};
}
test('capture keeps every non-waste field and does not mutate the original',()=>{const s=session(),before=JSON.stringify(ordinary);s.add(good,ordinary,profile,'row1');const d=s.capture(ordinary,profile);assert.equal(JSON.stringify(ordinary),before);const rest={...d};delete rest[B.KEY];assert.deepEqual(rest,ordinary);assert.equal(d[B.KEY].entries[0].id,'row1');});
test('legacy report remains exactly unchanged when no general-waste rows are added',()=>{const s=session();s.load(ordinary,profile);assert.deepEqual(s.capture(ordinary,profile),ordinary);});
test('JSON save/reopen retains numeric strings, ticket and stable record ID',()=>{const s=session();s.add({...good,quantity:'000.250',unit:'t',netKg:'250',ticketNumber:'00001'},ordinary,profile,'row1');const d=JSON.parse(JSON.stringify(s.capture(ordinary,profile))),r=session();r.load(d,profile);assert.deepEqual(r.capture(ordinary,profile)[B.KEY],d[B.KEY]);});
test('editing one row updates it, not a second copy',()=>{const s=session();s.add(good,ordinary,profile,'r');s.update('r',{netKg:'280'},profile);assert.equal(s.entries(profile).length,1);assert.equal(s.entries(profile)[0].netKg,'280');});
test('draft restore keeps a partial value for later completion',()=>{const s=session();s.add({...good,netKg:'',quantity:'1.'},ordinary,profile,'r');const saved=s.capture(ordinary,profile),r=session();r.load(saved,profile,'restore');assert.equal(r.entries(profile)[0].quantity,'1.');const m=B.monthlyFromReports(M,[report(r)],'2026-09',profile,review);assert.equal(m.ready,false);assert.equal(m.totalKg,'0');assert.ok(m.issues.length);});
test('duplicating a daily report does not copy deliveries or weigh-slip numbers',()=>{const s=session();s.add(good,ordinary,profile,'r');const r=session();r.load(s.capture(ordinary,profile),profile,'duplicate');const next=r.capture({...ordinary,id:2},profile);assert.equal(next[B.KEY],undefined);assert.deepEqual(next.items,ordinary.items);assert.deepEqual(next.siteMoves,ordinary.siteMoves);});
test('date/site changes do not silently reassign a recorded delivery',()=>{const s=session();s.add(good,ordinary,profile,'r');const d=s.capture({...ordinary,date:'2026-09-25',site:'別現場'},profile);assert.equal(d[B.KEY].entries[0].date,'2026-09-24');assert.equal(d[B.KEY].entries[0].siteName,'検証現場');});
test('entry snapshots cannot mutate the live editing session',()=>{const s=session();s.add(good,ordinary,profile,'r');s.entries(profile)[0].netKg='999';assert.equal(s.entries(profile)[0].netKg,'250');});
test('removal needs confirmation and retains an explicit empty envelope',()=>{const s=session();s.add(good,ordinary,profile,'r');assert.throws(()=>s.remove('r',profile),/確認/);assert.equal(s.entries(profile).length,1);s.remove('r',profile,true);assert.deepEqual(s.capture(ordinary,profile)[B.KEY].entries,[]);});
test('company switch cannot copy old company records',()=>{const s=session();s.add(good,ordinary,profile,'r');assert.throws(()=>s.capture(ordinary,{...profile,companyId:'other'}),/切り替わり/);assert.equal(s.value,null);});
test('sign-out clears the session before refusing collection',()=>{const s=session();s.add(good,ordinary,profile,'r');assert.throws(()=>s.capture(ordinary,{...profile,active:false}),/ログイン/);assert.equal(s.value,null);});
test('cross-company envelope and unknown versions are rejected rather than dropped',()=>{const s=session();s.add(good,ordinary,profile,'r');const d=s.capture(ordinary,profile),other=structuredClone(d);other[B.KEY].companyId='other';assert.throws(()=>session().load(other,profile),/会社/);d[B.KEY].version=2;assert.throws(()=>session().load(d,profile),/形式/);});
test('record identity and waste class cannot be patched',()=>{const s=session();s.add(good,ordinary,profile,'r');for(const patch of [{id:'new'},{companyId:'other'},{wasteClass:'industrial'}])assert.throws(()=>s.update('r',patch,profile),/変更できません/);assert.equal(s.entries(profile)[0].id,'r');});
test('duplicate row IDs fail atomically',()=>{const s=session();s.add(good,ordinary,profile,'r');assert.throws(()=>s.add(good,ordinary,profile,'r'),/記録ID/);assert.equal(s.entries(profile).length,1);});
test('future metadata survives an unchanged edit roundtrip',()=>{const s=session();s.add(good,ordinary,profile,'r');const d=s.capture(ordinary,profile);d[B.KEY].futureOption={keep:1};d[B.KEY].entries[0].futureExtra='keep';s.load(d,profile);s.update('r',{netKg:'251'},profile);const v=s.snapshot(profile);assert.deepEqual(v.futureOption,{keep:1});assert.equal(v.entries[0].futureExtra,'keep');});
test('monthly summary collects general waste exactly once, separately from industrial items',()=>{const s=session();s.add(good,ordinary,profile,'r1');s.add({...good,type:'不燃物',facility:'横井処分',quantity:'0.12',unit:'t',netKg:'',massConfirmed:true,ticketNumber:'TEST-2'},ordinary,profile,'r2');s.add({...good,type:'粗大ごみ',facility:'粗大ごみ処理棟',netKg:'60',facilitySectionConfirmed:true,ticketNumber:'TEST-3'},ordinary,profile,'r3');const m=B.monthlyFromReports(M,[report(s),report(s)],'2026-09',profile,review);assert.equal(m.totalKg,'430');assert.equal(m.ready,true);assert.equal(m.totals.north,'250');assert.equal(m.totals.yokoi,'120');assert.equal(m.totals.bulky,'60');assert.equal(m.accepted.length,3);});
test('unconfirmed permit-scope data is withheld and cannot become a zero report',()=>{const s=session();s.add({...good,scopeConfirmed:false},ordinary,profile,'r');const m=B.monthlyFromReports(M,[report(s)],'2026-09',profile,{...review,explicitZero:true});assert.equal(m.totalKg,'0');assert.equal(m.ready,false);assert.equal(m.zeroConfirmed,false);});
test('volume-only data stays unconfirmed; it is never converted to weight',()=>{const s=session();s.add({...good,unit:'m³',quantity:'4',netKg:''},ordinary,profile,'r');const m=B.monthlyFromReports(M,[report(s)],'2026-09',profile,review);assert.equal(m.ready,false);assert.equal(m.totalKg,'0');});
test('same weigh slip on different row IDs is withheld for reconciliation',()=>{const s=session();s.add(good,ordinary,profile,'r1');s.add(good,ordinary,profile,'r2');const m=B.monthlyFromReports(M,[report(s)],'2026-09',profile,review);assert.equal(m.ready,false);assert.equal(m.totalKg,'0');assert.equal(m.issues.length,2);});
test('old reports are not automatically declared zero general waste',()=>{const m=B.monthlyFromReports(M,[{id:'old',company_id:profile.companyId,report_data:ordinary}],'2026-09',profile,{...review,legacyReportsReconciled:false,explicitZero:true});assert.equal(m.ready,false);assert.equal(m.coverage.legacyReports,1);});
test('other-company reports never enter the extraction',()=>{const s=session();s.add(good,ordinary,profile,'r');const d=report(s);d.company_id='other';assert.equal(B.extractReports([d],profile.companyId).records.length,0);});
test('old-client omission is rejected by the proposed guard contract (not deployed)',()=>{const s=session();s.add(good,ordinary,profile,'r');assert.throws(()=>B.assertWritePreserves(s.capture(ordinary,profile),ordinary),/更新版/);assert.equal(B.assertWritePreserves(ordinary,ordinary),true);});
test('existing app collect/fill/normalize cooperate with the staged wrapper',()=>{const {host,$}=fixture();let changes=0;const api=B.bind(host,{getProfile:()=>profile,onChange:()=>changes++});api.add(good,'r');const collected=host.collect();assert.equal(collected[B.KEY].entries[0].netKg,'250');const saved={id:'cloud1',company_id:profile.companyId,source_report_id:String(collected.id),report_date:collected.date,report_data:JSON.parse(JSON.stringify(collected))};const normalized=host.cloudNormalizeReport(saved);host.fillReportForm(normalized,'edit');assert.equal(api.entries()[0].id,'r');$('#details').value='編集後の本文';assert.equal(host.collect().details,'編集後の本文');assert.equal(host.collect()[B.KEY].entries[0].netKg,'250');host.fillReportForm({...normalized,id:2,cloudId:null},'duplicate');assert.equal(api.entries().length,0);assert.equal(host.collect()[B.KEY],undefined);assert.ok(changes>=3);});
test('existing app draft restoration retains the extension and save reset clears it',()=>{const {host}=fixture();const api=B.bind(host,{getProfile:()=>profile});api.add(good,'r');const draft=JSON.parse(JSON.stringify(host.collect()));host.clearReportEditState();assert.equal(api.entries().length,0);host.fillReportForm(draft,'edit');assert.equal(api.entries()[0].ticketNumber,'TEST-1');host.clearReportEditState();assert.equal(host.collect()[B.KEY],undefined);});
test('bridge cannot install twice or invoke network/storage on its own',()=>{const {host}=fixture();let writes=0;host.cloudClient=new Proxy({},{get(){writes++;throw Error('no network');}});host.localStorage=new Proxy({},{get(){writes++;throw Error('no storage');}});const api=B.bind(host,{getProfile:()=>profile});api.add(good,'r');host.collect();assert.equal(writes,0);assert.throws(()=>B.bind(host,{getProfile:()=>profile}),/接続済み/);});
