-- Execute inside BEGIN/ROLLBACK with toya.qa_admin and toya.qa_employee set.
-- Only newly-created QA records are modified. Never commits test records.
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_admin'),'role','authenticated')::text,true);
do $$
declare c uuid; s public.sites; d public.project_documents; v public.project_documents;
 j jsonb; blocked boolean; n integer; result uuid;
begin
 select company_id into c from public.profiles where id=auth.uid();
 insert into public.sites(company_id,name) values(c,'QA rollback only - invoice deletion') returning * into s;
 j:=jsonb_build_object('site_id',s.id,'kind','invoice','document_date',current_date,'transaction_end',current_date,'due_date',current_date+30,'customer_name','QA sample','subject','QA deletion','issuer',jsonb_build_object('issuer_name','QA issuer'),'items',jsonb_build_array(jsonb_build_object('name','QA work','quantity','1','unitPrice','1000','unit','式')),'tax_rate',10);
 d:=public.toya_save_project_document(gen_random_uuid(),null,j);
 blocked:=false;
 begin perform public.toya_delete_unissued_invoice(d.id,d.updated_at-interval '1 second'); exception when others then blocked:=sqlerrm like '%更新%'; end;
 if not blocked or not exists(select 1 from public.project_documents where id=d.id) then raise exception 'FAIL stale version'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_employee'),'role','authenticated')::text,true);
 blocked:=false;
 begin perform public.toya_delete_unissued_invoice(d.id,d.updated_at); exception when others then blocked:=sqlerrm like '%管理者%'; end;
 if not blocked then raise exception 'FAIL employee RPC'; end if;
 delete from public.project_documents where id=d.id;get diagnostics n=row_count;
 if n<>0 then raise exception 'FAIL employee direct delete'; end if;
 perform set_config('request.jwt.claims','{}',true);
 blocked:=false;
 begin perform public.toya_delete_unissued_invoice(d.id,d.updated_at); exception when others then blocked:=sqlerrm like '%管理者%'; end;
 if not blocked then raise exception 'FAIL missing identity'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_admin'),'role','authenticated')::text,true);
 result:=public.toya_delete_unissued_invoice(d.id,d.updated_at);
 if result<>d.id or exists(select 1 from public.project_documents where id=d.id) then raise exception 'FAIL draft deletion'; end if;
 d:=public.toya_save_project_document(gen_random_uuid(),null,j);
 d:=public.toya_void_project_document(d.id,d.updated_at,'QA unused draft');
 result:=public.toya_delete_unissued_invoice(d.id,d.updated_at);
 if result<>d.id or exists(select 1 from public.project_documents where id=d.id) then raise exception 'FAIL unissued cancellation deletion'; end if;
 d:=public.toya_save_project_document(gen_random_uuid(),null,j);
 d:=public.toya_issue_project_document(d.id,d.updated_at);
 blocked:=false;
 begin perform public.toya_delete_unissued_invoice(d.id,d.updated_at); exception when others then blocked:=sqlerrm like '%一度も確定%'; end;
 if not blocked then raise exception 'FAIL issued RPC deletion'; end if;
 delete from public.project_documents where id=d.id;get diagnostics n=row_count;
 if n<>0 then raise exception 'FAIL issued direct deletion'; end if;
 d:=public.toya_void_project_document(d.id,d.updated_at,'QA issued cancellation');
 blocked:=false;
 begin perform public.toya_delete_unissued_invoice(d.id,d.updated_at); exception when others then blocked:=sqlerrm like '%一度も確定%'; end;
 if not blocked then raise exception 'FAIL issued-then-void deletion'; end if;
 delete from public.project_documents where id=d.id;get diagnostics n=row_count;
 if n<>0 then raise exception 'FAIL issued-then-void direct deletion'; end if;
 v:=public.toya_save_project_document(gen_random_uuid(),null,j||jsonb_build_object('kind','estimate'));
 blocked:=false;
 begin perform public.toya_delete_unissued_invoice(v.id,v.updated_at); exception when others then blocked:=sqlerrm like '%一度も確定%'; end;
 if not blocked then raise exception 'FAIL estimate deletion'; end if;
 delete from public.project_documents where id=v.id;get diagnostics n=row_count;
 if n<>0 then raise exception 'FAIL estimate direct deletion'; end if;
 if has_function_privilege('anon','public.toya_delete_unissued_invoice(uuid,timestamptz)','EXECUTE') then raise exception 'FAIL anon execute'; end if;
end $$;
reset role;
select 'PASS: draft and unissued cancellation deletion, role restrictions, version conflict, issued history, direct DELETE RLS' as result;
