const assert=require('node:assert/strict');
const C=require('../docs/estimate-plan-engine.js'),E=require('../docs/project-documents-engine.js');
const row=(q,m,p,category='labor')=>({category,label:'施工費用',quantity:String(q),multiplier:String(m),unit:'人日',unit_price:String(p)});
const plan=(groups,extra={})=>({groups,overhead_percent:'10',markup_percent:'20',quote_amount_override:null,tax_rate:10,...extra});
let n=0;function test(name,fn){fn();console.log('PASS '+name);n++;}
test('人数 × 日数 × 単価、諸経費、利益上乗せ',()=>{const t=C.calculate(plan([{name:'内装解体',lines:[row(3,2,20000)]},{name:'運搬処分',lines:[row(10,1,1000,'waste')]}]));assert.equal(t.known_cost,130000);assert.equal(t.overhead,13000);assert.equal(t.total_cost,143000);assert.equal(t.price,171600);assert.equal(t.profit,28600);assert.equal(t.total,188760);assert.equal(E.total(t.quote_items,10).cost,t.total_cost);assert.equal(E.total(t.quote_items,10).total,t.total);});
test('小数の数量・回数・単価を整数演算で切り捨て',()=>{assert.equal(C.line(row('1.125','2.375','19.99')).amount,53);assert.equal(C.line(row('0.29','1','100')).amount,29);});

test('未入力の内訳をゼロ円確定せず途中保存',()=>{const t=C.calculate(plan([{name:'解体',lines:[row(2,1,1000),row(1,1,'')]}]));assert.equal(t.complete,false);assert.equal(t.known_cost,2000);assert.equal(t.price,null);assert.equal(t.pending,1);});
test('諸経費・上乗せ率も明示的な0で確定',()=>{const p=plan([{name:'作業',lines:[row(1,1,0)]}],{overhead_percent:null,markup_percent:null});assert.equal(C.calculate(p).pending,2);Object.assign(p,{overhead_percent:0,markup_percent:0});assert.equal(C.calculate(p).price,0);});
test('見積調整で損失も正しく表示、工事項目への配分で端数を保存',()=>{const t=C.calculate(plan([{name:'A',lines:[row(1,1,1)]},{name:'B',lines:[row(1,1,1)]},{name:'C',lines:[row(1,1,1)]}],{overhead_percent:34,markup_percent:0,quote_amount_override:2}));assert.equal(t.overhead,1);assert.equal(t.profit,-2);assert.equal(t.groups.reduce((n,g)=>n+g.overhead,0),1);assert.equal(t.groups.reduce((n,g)=>n+g.price,0),2);assert.equal(E.total(t.quote_items,10).subtotal,2);});
test('原価0の各工事項目にも見積調整額を等分',()=>{const t=C.calculate(plan([{name:'A',lines:[row(1,1,0)]},{name:'B',lines:[row(1,1,0)]}],{overhead_percent:0,markup_percent:0,quote_amount_override:101}));assert.deepEqual(t.groups.map(g=>g.price),[50,51]);});
test('負数・過大金額・小数桁の不正を拒否',()=>{for(const r of [row(-1,1,1),row(0,1,1),row(1,1,'1.001'),row(1000000,1000000,1000000),row(1,1,'NaN')])assert.throws(()=>C.line(r));assert.throws(()=>C.calculate(plan([{name:'A',lines:[row(1,1,1)]}],{quote_amount_override:'0.5'})));});
test('複製は元の積算・現場・日付を変更しない',()=>{const p={...C.draft({id:'old-site',name:'完工現場'}),id:'original',company_id:'c',updated_at:'v1'};const c=C.duplicate(p,{id:'new-site',name:'次の現場'});c.groups[0].name='新しい作業';assert.equal(p.groups[0].name,'');assert.equal(c.site_id,'new-site');assert.equal(c.source_plan_id,'original');assert.equal(c.id,undefined);assert.equal(c.updated_at,undefined);});
test('燃料を重機に別加算する',()=>{const t=C.calculate(plan([{name:'重機作業',lines:[row(1,2,30000,'equipment'),row(50,1,150,'fuel')]}],{overhead_percent:0,markup_percent:0}));assert.equal(t.known_cost,67500);});
test('見積には内部費用・社内メモを印刷しない',()=>{const p=plan([{name:'解体工事',lines:[{...row(3,1,20000),label:'社内人工原価'}]}],{title:'試験見積',internal_notes:'社内の施工条件',quote_notes:'見積条件'});const t=C.calculate(p);const html=E.printHTML({...E.draft('estimate',{id:'s',name:'試験現場'},{issuer_name:'試験工業'},'2026-09-11'),items:t.quote_items,notes:p.quote_notes,estimate_snapshot:p});assert.ok(!html.includes('社内人工原価'));assert.ok(!html.includes('社内の施工条件'));assert.ok(html.includes('見積条件'));const internal=C.printHTML(p,'試験現場');assert.ok(internal.includes('社内人工原価'));assert.ok(internal.includes('社内の施工条件'));});
test('工事項目・内容をエスケープして印刷',()=>{const p=plan([{name:'<script>bad</script>',lines:[{...row(1,1,1),label:'<img src=x>'}]}]);assert.ok(C.printHTML(p,'<x>').includes('&lt;script&gt;'));assert.ok(!C.printHTML(p,'<x>').includes('<script>bad'));});
console.log(n+' estimating tests passed');
