-- Run with test identities in a transaction and ALWAYS roll back.
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_admin'),'role','authenticated')::text,true);
do $$
declare c uuid; old_site public.sites; next_site public.sites; p public.estimate_plans; copied public.estimate_plans; d public.project_documents; issued public.project_documents; changed public.estimate_plans; j jsonb; original jsonb; blocked boolean; count_changed integer;
begin
 select company_id into c from public.profiles where id=auth.uid();
 insert into public.sites(company_id,name,status,completed_on) values(c,'QA transaction only - old estimate','inactive','2026-09-01') returning * into old_site;
 insert into public.sites(company_id,name) values(c,'QA transaction only - next estimate') returning * into next_site;
 j:=jsonb_build_object('site_id',old_site.id,'title','QA construction estimate','customer_name','QA recipient','internal_notes','QA private assumption','quote_notes','QA customer conditions','groups',jsonb_build_array(jsonb_build_object('name','QA demolition','lines',jsonb_build_array(jsonb_build_object('category','labor','label','QA internal crew','quantity','3','multiplier','2','unit','人日','unit_price','20000')))),'overhead_percent',null,'markup_percent',null,'tax_rate',10);
 p:=public.toya_save_estimate_plan(gen_random_uuid(),null,j);
 if (p.calculation->>'complete')::boolean or p.calculation->'price'<>'null'::jsonb or (p.calculation->>'known_cost')::numeric<>120000 then raise exception 'FAIL incomplete cost plan'; end if;
 blocked:=false;
 begin perform public.toya_create_estimate_document(p.id,p.updated_at,gen_random_uuid()); exception when others then blocked:=sqlerrm like '%未入力%'; end;
 if not blocked then raise exception 'FAIL incomplete estimate source'; end if;
 j:=j||jsonb_build_object('overhead_percent',10,'markup_percent',20);
 p:=public.toya_save_estimate_plan(p.id,p.updated_at,j);
 if (p.calculation->>'price')::numeric<>158400 or (p.calculation->>'total_cost')::numeric<>132000 then raise exception 'FAIL cost plan calculation'; end if;
 blocked:=false;
 begin perform public.toya_save_estimate_plan(p.id,p.updated_at-interval '1 second',j); exception when others then blocked:=sqlerrm like '%更新%'; end;
 if not blocked then raise exception 'FAIL stale cost plan save'; end if;
 original:=to_jsonb(p);
 copied:=public.toya_save_estimate_plan(gen_random_uuid(),null,j||jsonb_build_object('site_id',next_site.id,'source_plan_id',p.id));
 if copied.source_plan_id<>p.id or copied.site_id<>next_site.id or to_jsonb((select s from public.estimate_plans s where id=p.id))<>original then raise exception 'FAIL preserve completed site plan on copy'; end if;
 blocked:=false;
 begin update public.estimate_plans set site_id=next_site.id where id=p.id; exception when others then blocked:=sqlerrm like '%複製%'; end;
 if not blocked then raise exception 'FAIL moving original site'; end if;
 d:=public.toya_create_estimate_document(copied.id,copied.updated_at,gen_random_uuid());
 if d.subtotal<>158400 or d.cost_total<>132000 or d.total<>174240 or d.estimate_plan_id<>copied.id or d.estimate_snapshot->>'internal_notes'<>'QA private assumption' or d.notes<>'QA customer conditions' or d.items->0->>'name'<>'QA demolition' then raise exception 'FAIL estimate snapshot and selling amounts'; end if;
 if exists(select 1 from public.revenues where site_id=next_site.id) then raise exception 'FAIL estimate created revenue'; end if;
 if (public.toya_create_estimate_document(copied.id,copied.updated_at,d.id)).id<>d.id then raise exception 'FAIL idempotent generation'; end if;
 blocked:=false;
 begin update public.project_documents set items=jsonb_set(items,'{0,unitPrice}','"1"') where id=d.id; exception when others then blocked:=sqlerrm like '%積算表%'; end;
 if not blocked then raise exception 'FAIL source estimate amount mutation'; end if;
 -- metadata remains editable while source amounts stay fixed.
 d:=public.toya_save_project_document(d.id,d.updated_at,to_jsonb(d)||jsonb_build_object('valid_until','2026-10-31','issuer',jsonb_build_object('issuer_name','QA issuer')));
 issued:=public.toya_issue_project_document(d.id,d.updated_at);
 if issued.status<>'issued' or issued.document_number !~ '^EST-2026-' then raise exception 'FAIL issue estimate'; end if;
 changed:=public.toya_save_estimate_plan(copied.id,copied.updated_at,to_jsonb(copied)||jsonb_build_object('quote_amount_override',150000));
 if (select subtotal from public.project_documents where id=d.id)<>158400 or (select estimate_snapshot from public.project_documents where id=d.id)<>d.estimate_snapshot then raise exception 'FAIL historical quote changed'; end if;
 if (public.toya_create_estimate_document(copied.id,copied.updated_at,d.id)).id<>d.id then raise exception 'FAIL retry after plan edit'; end if;
 blocked:=false;
 begin perform public.toya_create_estimate_document(copied.id,copied.updated_at,gen_random_uuid()); exception when others then blocked:=sqlerrm like '%更新%'; end;
 if not blocked then raise exception 'FAIL stale source generation'; end if;
 d:=public.toya_create_estimate_document(changed.id,changed.updated_at,gen_random_uuid());
 if d.subtotal<>150000 then raise exception 'FAIL new quote revision'; end if;
 update public.estimate_plans set calculation='{}' where id=changed.id returning * into changed;
 if (changed.calculation->>'price')::numeric<>150000 then raise exception 'FAIL forged totals'; end if;
 blocked:=false;
 begin perform public.toya_save_estimate_plan(gen_random_uuid(),null,j||jsonb_build_object('site_id',gen_random_uuid())); exception when others then blocked:=sqlerrm like '%現場%'; end;
 if not blocked then raise exception 'FAIL inaccessible site'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_employee'),'role','authenticated')::text,true);
 if exists(select 1 from public.estimate_plans) or exists(select 1 from public.project_documents where estimate_plan_id is not null) then raise exception 'FAIL employee visibility'; end if;
 blocked:=false;
 begin perform public.toya_save_estimate_plan(gen_random_uuid(),null,j); exception when others then blocked:=sqlerrm like '%管理者%'; end;
 if not blocked then raise exception 'FAIL employee save'; end if;
 blocked:=false;
 begin perform public.toya_create_estimate_document(changed.id,changed.updated_at,gen_random_uuid()); exception when others then blocked:=sqlerrm like '%管理者%'; end;
 if not blocked then raise exception 'FAIL employee quote generation'; end if;
 update public.estimate_plans set title='employee mutation' where id=changed.id;get diagnostics count_changed=row_count;
 if count_changed<>0 then raise exception 'FAIL employee direct update'; end if;
end $$;
