const assert=require('node:assert/strict');
const {setup,pause}=require('./project-business-ui.cjs');

(async()=>{
 const {dom,w,db}=await setup('admin',true),q=s=>w.document.querySelector(s);
 const set=(selector,value)=>{q(selector).value=value;q(selector).dispatchEvent(new w.Event(q(selector).tagName==='SELECT'?'change':'input',{bubbles:true}));};
 const byLabel=label=>[...w.document.querySelectorAll('[data-quote-row]')].find(r=>r.querySelector('[data-quote-key="label"]')?.value===label);
 const quantity=label=>byLabel(label)?.querySelector('[data-quote-key="quantity"]').value;
 q('#epNew').click();set('#epJobName','参考数量検証');set('#epCustomer','試験見積先');q('#epNextItems').click();
 set('#epAutoM2','300');assert.equal(q('#epAutoTsubo').value,'90.75');
 assert.equal(q('#epAutoFoundation').value,'');set('#epAutoFloors','3');assert.match(q('#epAutoConcreteSummary').textContent,/61.5 t/);
 set('#epAutoKind','rc');assert.match(q('#epAutoConcreteSummary').textContent,/339.9 t/);
 set('#epAutoAreaBasis','typical');set('#epAutoM2','100');assert.match(q('#epAutoConcreteSummary').textContent,/339.9 t/);
 set('#epAutoUse','office');assert.match(q('#epAutoConcreteSummary').textContent,/498.9 t/);assert.match(q('#epAutoConcreteSummary').textContent,/資材投入量/);
 set('#epAutoUpperMethod','elevated');set('#epAutoElevatedArea','200');set('#epAutoSamples','2');q('#epAutoApply').click();
 assert.equal(quantity('RC造 階上解体'),'200');assert.equal(quantity('RC造 上屋解体'),'100');
 assert.equal(quantity('コンクリート処分費'),'498.9');assert.equal(byLabel('コンクリート処分費').querySelector('[data-quote-key="unit"]').value,'t');
 assert.equal(byLabel('コンクリート処分費').querySelector('[data-quote-key="quote_price"]').value,'');
 assert.equal(quantity('アスベスト含有調査'),'2');
 q('#epSave').click();await pause();const id=db.estimate_plans[0].id;
 assert.equal(db.estimate_plans[0].groups[0].auto_input.concrete_reference.factor_kg_m2,1663);
 q('#epNew').click();q('[data-ep-open="'+id+'"]').click();
 assert.equal(q('#epAutoAreaBasis').value,'typical');assert.equal(q('#epAutoUse').value,'office');assert.equal(q('#epAutoElevatedArea').value,'200');
 assert.equal(quantity('コンクリート処分費'),'498.9','再読込で保存済み明細を再生成しない');
 set('#epAutoConcreteMode','manual');set('#epAutoConcreteQuantity','12.5');set('#epAutoConcreteUnit','solid_m3');set('#epAutoConcreteDisposal','4000');set('#epAutoFoundation','0');q('#epAutoApply').click();q('#epSave').click();await pause();
 assert.equal(q('#epAutoConcreteMode').value,'manual');assert.equal(q('#epAutoConcreteQuantity').value,'12.5');assert.equal(q('#epAutoFoundation').value,'0');
 set('#epAutoFloors','4');assert.equal(q('#epAutoConcreteQuantity').value,'12.5');assert.equal(q('#epAutoFoundation').value,'0');
 assert.match(q('#epAutoConcretePriceNote').textContent,/円\/m³/);
 set('#epAutoConcreteMode','reference');assert.equal(q('#epAutoConcreteDisposal').value,'','単位変更時に既存単価をクリア');
 set('#epAutoConcreteMode','manual');set('#epAutoConcreteQuantity','0');q('#epAutoApply').click();assert.equal(quantity('コンクリート処分費'),undefined);q('#epSave').click();await pause();assert.equal(q('#epAutoConcreteQuantity').value,'0');
 set('#epAutoConcreteMode','reference');set('#epAutoConcreteScope','partial');q('#epAutoApply').click();assert.equal(quantity('コンクリート処分費'),'');assert.match(q('#epAutoConcreteSummary').textContent,/手入力/);
 q('#epSave').click();await pause();assert.equal(db.estimate_plans[0].calculation.complete,false);
 dom.window.close();console.log('PASS UI: concrete reference, elevated areas, saving, manual overrides, zero and unit changes');
})().catch(e=>{console.error(e);process.exitCode=1;});
