-- Set toya.qa_admin / toya.qa_employee and always run inside BEGIN / ROLLBACK.
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_admin'),'role','authenticated')::text,true);
do $$
declare c uuid; j jsonb; p public.estimate_plans; revised public.estimate_plans; d public.project_documents; issued public.project_documents; next_doc public.project_documents; blocked boolean; site_count integer; revenue_count integer;
begin
 select company_id into c from public.profiles where id=auth.uid();
 select count(*) into site_count from public.sites where company_id=c;
 select count(*) into revenue_count from public.revenues where company_id=c;
 j:=jsonb_build_object('site_id',null,'site_name','QA new job','site_address','QA job address','title','QA new estimate','customer_name','QA customer','groups','[{"name":"QA floor work","lines":[{"category":"other","label":"QA floor","quantity":"21.60","multiplier":"1","unit":"m²","unit_price":""}]}]'::jsonb,'tax_rate',10);
 blocked:=false;
 begin perform public.toya_save_estimate_plan(gen_random_uuid(),null,j||'{"site_name":""}'::jsonb); exception when others then blocked:=sqlerrm like '%工事名%'; end;
 if not blocked then raise exception 'FAIL unnamed new job accepted'; end if;
 p:=public.toya_save_estimate_plan(gen_random_uuid(),null,j);
 if p.site_id is not null or p.site_name<>'QA new job' or p.site_address<>'QA job address' or (p.calculation->>'complete')::boolean then raise exception 'FAIL independent incomplete estimate'; end if;
 j:=jsonb_set(j,'{groups,0,lines,0,unit_price}','"1000"')||'{"overhead_percent":10,"markup_percent":20}'::jsonb;
 p:=public.toya_save_estimate_plan(p.id,p.updated_at,j);
 if (p.calculation->>'price')::numeric<>28512 then raise exception 'FAIL new job calculation'; end if;
 d:=public.toya_create_estimate_document(p.id,p.updated_at,gen_random_uuid());
 if d.site_id is not null or d.site_name<>p.site_name or d.site_address<>p.site_address or d.subtotal<>28512 or d.estimate_snapshot->>'site_name'<>p.site_name then raise exception 'FAIL new job document snapshot'; end if;
 d:=public.toya_save_project_document(d.id,d.updated_at,to_jsonb(d)||jsonb_build_object('issuer',jsonb_build_object('issuer_name','QA issuer'),'valid_until','2026-12-31'));
 issued:=public.toya_issue_project_document(d.id,d.updated_at);
 if issued.status<>'issued' or issued.document_number !~ '^EST-[0-9]{4}-[0-9]+$' or issued.site_address<>'QA job address' then raise exception 'FAIL issuing new job estimate'; end if;
 if (public.toya_issue_project_document(issued.id,issued.updated_at)).id<>issued.id then raise exception 'FAIL issue retry'; end if;
 revised:=public.toya_save_estimate_plan(p.id,p.updated_at,j||'{"site_name":"QA revised job","site_address":"QA revised address"}'::jsonb);
 if (select site_name from public.project_documents where id=issued.id)<>'QA new job' or (select site_address from public.project_documents where id=issued.id)<>'QA job address' then raise exception 'FAIL changed issued job metadata'; end if;
 next_doc:=public.toya_create_estimate_document(revised.id,revised.updated_at,gen_random_uuid());
 if next_doc.site_name<>'QA revised job' then raise exception 'FAIL revised quote job'; end if;
 blocked:=false;
 begin update public.project_documents set site_address='QA forbidden rewrite' where id=issued.id; exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL editable issued job address'; end if;
 blocked:=false;
 begin perform public.toya_save_project_document(gen_random_uuid(),null,to_jsonb(d)||'{"kind":"invoice"}'::jsonb); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL invoice without operational site'; end if;
 blocked:=false;
 begin perform public.toya_estimate_to_contract(issued.id,null); exception when others then blocked:=sqlerrm like '%受注%'; end;
 if not blocked then raise exception 'FAIL new quote turned into sales without site'; end if;
 blocked:=false;
 begin insert into public.project_documents(company_id,site_id,kind,site_name,estimate_plan_id) values(c,gen_random_uuid(),'estimate','QA mismatch',p.id); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL mismatched quote source site'; end if;
 if (select count(*) from public.sites where company_id=c)<>site_count or (select count(*) from public.revenues where company_id=c)<>revenue_count then raise exception 'FAIL new estimate changed sites or revenue'; end if;
 d:=public.toya_void_project_document(issued.id,issued.updated_at,'QA cancellation');
 if d.status<>'void' then raise exception 'FAIL independent estimate cancellation'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_employee'),'role','authenticated')::text,true);
 if exists(select 1 from public.estimate_plans) or exists(select 1 from public.project_documents) then raise exception 'FAIL employee financial visibility'; end if;
 blocked:=false;
 begin perform public.toya_save_estimate_plan(gen_random_uuid(),null,j); exception when others then blocked:=sqlerrm like '%管理者%'; end;
 if not blocked then raise exception 'FAIL employee new quote'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',gen_random_uuid(),'role','authenticated')::text,true);
 if exists(select 1 from public.estimate_plans) or exists(select 1 from public.project_documents) then raise exception 'FAIL unknown identity financial visibility'; end if;
end $$;
reset role;
select 'PASS new job draft, calculation, snapshot, save, issue, immutable history, cancellation and role isolation' as result;
