-- Run in one transaction with toya.qa_admin / toya.qa_employee set to test users.
-- All records created here are rolled back by the runner, including on failure.
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_admin'),'role','authenticated')::text,true);
do $$
declare c uuid; s public.sites; e public.project_documents; i public.project_documents;
 a public.project_documents; b public.project_documents; r public.revenues;
 j jsonb; blocked boolean; changed integer;
begin
 select company_id into c from public.profiles where id=auth.uid();
 insert into public.sites(company_id,name) values(c,'QA transaction only - construction documents') returning * into s;
 j:=jsonb_build_object('site_id',s.id,'kind','estimate','document_date','2026-09-11','transaction_end','2026-09-11','due_date','2026-10-31','customer_name','QA customer','subject','QA construction','issuer',jsonb_build_object('issuer_name','QA issuer'),'items',jsonb_build_array(jsonb_build_object('name','QA work','quantity','10','unitPrice','10000','costPrice','6000','unit','式')),'tax_rate',10);
 e:=public.toya_save_project_document(gen_random_uuid(),null,j);
 if e.subtotal<>100000 or e.total<>110000 or e.cost_total<>60000 or e.document_number is not null then raise exception 'FAIL estimate totals'; end if;
 blocked:=false;
 begin perform public.toya_save_project_document(e.id,e.updated_at-interval '1 second',j); exception when others then blocked:=sqlerrm like '%更新%'; end;
 if not blocked then raise exception 'FAIL stale draft save'; end if;
 e:=public.toya_issue_project_document(e.id,e.updated_at);
 if e.document_number !~ '^EST-2026-[0-9]+$' then raise exception 'FAIL number generation'; end if;
 if (public.toya_issue_project_document(e.id,e.updated_at)).id<>e.id then raise exception 'FAIL repeat issue'; end if;
 r:=public.toya_estimate_to_contract(e.id,null);
 if r.amount<>100000 then raise exception 'FAIL estimate to contract'; end if;
 j:=jsonb_set(j,'{kind}','"invoice"');j:=jsonb_set(j,'{items,0,quantity}','"3"');
 i:=public.toya_save_project_document(gen_random_uuid(),null,j);i:=public.toya_issue_project_document(i.id,i.updated_at);
 j:=j||jsonb_build_object('kind','progress','cumulative_amount',70000);
 a:=public.toya_save_project_document(gen_random_uuid(),null,j);
 if a.previous_billed<>30000 or a.subtotal<>40000 or a.total<>44000 then raise exception 'FAIL progress deduction'; end if;
 b:=public.toya_save_project_document(gen_random_uuid(),null,j||jsonb_build_object('cumulative_amount',50000));
 b:=public.toya_issue_project_document(b.id,b.updated_at);
 blocked:=false;
 begin perform public.toya_issue_project_document(a.id,a.updated_at); exception when others then blocked:=sqlerrm like '%変わりました%'; end;
 if not blocked then raise exception 'FAIL competing progress draft'; end if;
 a:=public.toya_save_project_document(a.id,a.updated_at,j);a:=public.toya_issue_project_document(a.id,a.updated_at);
 if a.previous_billed<>50000 or a.subtotal<>20000 then raise exception 'FAIL progress recalculation'; end if;
 if (select amount from public.revenues where id=r.id)<>100000 then raise exception 'FAIL invoice added revenue twice'; end if;
 blocked:=false;
 begin update public.project_documents set subject='changed' where id=a.id; exception when others then blocked:=sqlerrm like '%編集できません%'; end;
 if not blocked then raise exception 'FAIL issued edit'; end if;
 blocked:=false;
 begin perform public.toya_void_project_document(i.id,i.updated_at,'QA void'); exception when others then blocked:=sqlerrm like '%後の請求書%'; end;
 if not blocked then raise exception 'FAIL cancelling earlier billing'; end if;
 a:=public.toya_void_project_document(a.id,a.updated_at,'QA void latest');
 if a.status<>'void' or (select sum(subtotal) from public.project_documents where site_id=s.id and kind<>'estimate' and status='issued')<>50000 then raise exception 'FAIL void exclusion'; end if;
 blocked:=false;
 begin perform public.toya_save_project_document(gen_random_uuid(),null,j||jsonb_build_object('cumulative_amount',100001)); exception when others then blocked:=sqlerrm like '%累計出来高%'; end;
 if not blocked then raise exception 'FAIL overbilling guard'; end if;
 s:=public.toya_set_site_completion(s.id,s.lifecycle_version,'2026-09-11',false);
 if s.status<>'inactive' or s.completed_on<>'2026-09-11' then raise exception 'FAIL completion'; end if;
 blocked:=false;
 begin perform public.toya_set_site_completion(s.id,0,null,true); exception when others then blocked:=sqlerrm like '%更新%'; end;
 if not blocked then raise exception 'FAIL concurrent completion'; end if;
 s:=public.toya_set_site_completion(s.id,s.lifecycle_version,null,true);
 if s.status<>'active' or s.completed_on is not null then raise exception 'FAIL reopen'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('toya.qa_employee'),'role','authenticated')::text,true);
 if exists(select 1 from public.project_documents where site_id=s.id) then raise exception 'FAIL employee visibility'; end if;
 blocked:=false;
 begin perform public.toya_save_project_document(gen_random_uuid(),null,j); exception when others then blocked:=sqlerrm like '%管理者%'; end;
 if not blocked then raise exception 'FAIL employee write'; end if;
 update public.sites set completed_on='2026-09-11',status='inactive' where id=s.id;
 get diagnostics changed=row_count;
 if changed<>0 then raise exception 'FAIL employee completion'; end if;
end $$;
